-- Queries to find newest store and multi-category customers
-- Co-authored with CoCo
with store_rank as
(select storeid,storeopeningdate,row_number() over(order by storeopeningdate desc) as final_rank from dimstore)
select storeid from store_rank where final_rank=1;

-- find customers who have ordered from more than 3 categories in last 6 months

select customerid from (
select f.customerid,p.category from factorders f 
join dimdate d on f.dateid=d.dateid
join dimproduct p on f.productid=p.productid
where d.date>=dateadd(month,-6,'2024-7-31')) group by customerid having count(distinct category)>3;

-- month by total sales for current year
select d.month, sum(f.totalamount) as total_sales from factorders f 
join dimdate d on f.dateid=d.dateid
where d.year=2024 group by d.month;

-- highest discount given on any order in the last 1 year
select f.orderid,f.discountamount,row_number() over(order by discountamount desc) as rank from factorders f
join dimdate d on f.dateid=d.dateid
where d.date>=dateadd(year,-1,'2024-7-31') ;

 select sum(p.unitprice*f.quantityordered) from factorders f
 join dimproduct p on f.productid=p.productid;

 -- show customer id of customer who has taken maximum discount of lifetime
select customerid from factorders
group by customerid
order by sum(discountamount) desc limit 1;

-- list customers who have placed maximum order till date

select customerid,row_number() over(order by count(orderid) desc)
from factorders group by customerid limit 1;

-- show top 3 brands based on the sales of last year

select p.brand,row_number() over(order by sum(f.orderamount) desc) from factorders f
join dimdate d on f.dateid=d.dateid
join dimproduct p on f.productid=p.productid where d.date>=dateadd(year,-1,'2024-7-31') group by p.brand limit 3;

-- share the number of customers and their current loyalty program status

select l.programtier,count(c.customerid) as number_customers from dimcustomer c 
join dimloyaltyprogram l on c.loyaltyprogramid=l.loyaltyprogramid group by l.programtier;

-- show the top 5 products based on the quantity ordered in last 3 years

select p.productname,row_number() over(order by sum(f.quantityordered) desc) from factorders f
join dimdate d on f.dateid=d.dateid
join dimproduct p on f.productid=p.productid where d.date>=dateadd(year,-3,'2024-7-31') group by p.productname limit 5;

-- calculate the revenue generated by each store manager in june 2024;

select s.storename,sum(f.orderamount) as revenue_generated from factorders f
join dimdate d on f.dateid=d.dateid
join dimstore s on s.storeid=f.storeid where d.year='2024' and d.month=6 group by s.storename;